
version: '3.3'

services:
  nginx-prod:
    container_name: icart-back-nginx-prod
    build: compose/nginx
    volumes:
      - .:/app
    ports:
      - "8010:8001"
    depends_on:
      - api-prod

  api-prod:
    container_name: icart-back-api-prod
    build:
      dockerfile: prod.Dockerfile
    restart: always
    command: /start_prod
    volumes:
      - .:/app
    env_file: '.env.prod'
    depends_on:
      - database-prod

  database-prod:
    image: postgres:15-alpine
    container_name: icart-back-database-prod
    restart: always
    env_file: '.env.prod'
    user: root
    volumes:
      - icart_back_database_prod_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"

  minioprod:
    image: minio/minio:latest
    restart: always
    expose:
      - "9090"
      - "9000"
    ports:
      - "9091:9090"
      - "9001:9000"
    env_file:
      - ".env.prod"
    container_name: icartbackminioprod
    command: "server /data --address ':9000' --console-address ':9090'"

volumes:
  icart_back_database_prod_data:
