"""empty message

Revision ID: 4e3b3a3739c2
Revises: 328077678304
Create Date: 2023-09-30 01:45:58.715052

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4e3b3a3739c2"
down_revision: Union[str, None] = "328077678304"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
