"""empty message

Revision ID: e2ae7556a02d
Revises: e318f7bc552e
Create Date: 2023-10-17 08:51:53.833575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2ae7556a02d"
down_revision: Union[str, None] = "e318f7bc552e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_request",
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("birth_place", sa.String(), nullable=True),
        sa.Column("postal_code", sa.String(), nullable=True),
        sa.Column("father_name", sa.String(), nullable=True),
        sa.Column("tel", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("national_card_front_version_id", sa.String(), nullable=True),
        sa.Column("national_card_front_name", sa.String(), nullable=True),
        sa.Column("national_card_back_version_id", sa.String(), nullable=True),
        sa.Column("national_card_back_name", sa.String(), nullable=True),
        sa.Column("birth_certificate_version_id", sa.String(), nullable=True),
        sa.Column("birth_certificate_name", sa.String(), nullable=True),
        sa.Column("video_version_id", sa.String(), nullable=True),
        sa.Column("video_name", sa.String(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_request_id"), "user_request", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_request_id"), table_name="user_request")
    op.drop_table("user_request")
    # ### end Alembic commands ###
