"""empty message

Revision ID: 7c6f522d3dca
Revises: c513d192fe14
Create Date: 2023-10-08 09:50:53.013293

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7c6f522d3dca"
down_revision: Union[str, None] = "c513d192fe14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
