"""empty message

Revision ID: b1d923d5a869
Revises: 4ed0a2f3e6dd
Create Date: 2023-12-11 15:17:15.286711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1d923d5a869"
down_revision: Union[str, None] = "4ed0a2f3e6dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "capital_transfer_transaction_id_fkey",
        "capital_transfer",
        type_="foreignkey",
    )
    op.drop_column("capital_transfer", "transaction_id")
    op.add_column("deposit", sa.Column("card_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deposit", "card_number")
    op.add_column(
        "capital_transfer",
        sa.Column("transaction_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "capital_transfer_transaction_id_fkey",
        "capital_transfer",
        "transaction",
        ["transaction_id"],
        ["id"],
    )
    # ### end Alembic commands ###
