"""empty message

Revision ID: 3fe10f88bdab
Revises: d949a95a84af
Create Date: 2023-11-19 11:55:34.677770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3fe10f88bdab"
down_revision: Union[str, None] = "d949a95a84af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("card", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("card", "is_active")
    # ### end Alembic commands ###
