"""empty message

Revision ID: 547263f0c1b8
Revises: 993b660a650e
Create Date: 2023-10-04 05:15:23.993015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "547263f0c1b8"
down_revision: Union[str, None] = "993b660a650e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("merchant", sa.Column("number", sa.String(), nullable=False))
    op.create_index(op.f("ix_merchant_number"), "merchant", ["number"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_merchant_number"), table_name="merchant")
    op.drop_column("merchant", "number")
    # ### end Alembic commands ###
