"""empty message

Revision ID: 00c6dc6b54bb
Revises: e2da994dffb9
Create Date: 2023-11-11 11:59:44.405707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.transaction.models import (
    TransactionValueType,
    TransactionReasonEnum,
    TransactionStatusEnum,
)

# revision identifiers, used by Alembic.
revision: str = "00c6dc6b54bb"
down_revision: Union[str, None] = "e2da994dffb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_row",
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("receiver_id", sa.UUID(), nullable=False),
        sa.Column("transferor_id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["receiver_id"], ["wallet.id"]),
        sa.ForeignKeyConstraint(["transaction_id"], ["transaction.id"]),
        sa.ForeignKeyConstraint(["transferor_id"], ["wallet.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_row_id"),
        "transaction_row",
        ["id"],
        unique=True,
    )
    op.drop_constraint(
        "transaction_intermediary_id_fkey",
        "transaction",
        type_="foreignkey",
    )
    op.drop_column("transaction", "intermediary_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column("intermediary_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "transaction_intermediary_id_fkey",
        "transaction",
        "wallet",
        ["intermediary_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_transaction_row_id"), table_name="transaction_row")
    op.drop_table("transaction_row")
    # ### end Alembic commands ###
