"""empty message

Revision ID: 3e35f3c34b78
Revises: 358a1fe675d3
Create Date: 2023-11-08 15:15:04.488898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e35f3c34b78"
down_revision: Union[str, None] = "358a1fe675d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "capital_transfer",
        "value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "cash",
        "balance",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "cash",
        "received",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "cash",
        "consumed",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "cash",
        "transferred",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "cash",
        "debt",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.drop_column("cash", "paid")
    op.drop_column("cash", "remaining")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cash",
        sa.Column("remaining", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "cash",
        sa.Column("paid", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "cash",
        "debt",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "cash",
        "transferred",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "cash",
        "consumed",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "cash",
        "received",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "cash",
        "balance",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "capital_transfer",
        "value",
        existing_type=sa.BigInteger(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
