"""empty message

Revision ID: 0cdc092449b5
Revises: 33d0c2a039d3
Create Date: 2023-10-26 11:15:34.387323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0cdc092449b5"
down_revision: Union[str, None] = "33d0c2a039d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("position_request", sa.Column("reason", sa.String(), nullable=True))
    op.add_column("user_request", sa.Column("reason", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_request", "reason")
    op.drop_column("position_request", "reason")
    # ### end Alembic commands ###
