"""empty message

Revision ID: 2e268f7919c1
Revises: c7d83c3cd812
Create Date: 2023-12-03 09:37:05.377314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e268f7919c1"
down_revision: Union[str, None] = "c7d83c3cd812"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_location_name", table_name="location")
    op.create_index(op.f("ix_location_name"), "location", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_location_name"), table_name="location")
    op.create_index("ix_location_name", "location", ["name"], unique=False)
    # ### end Alembic commands ###
