"""empty message

Revision ID: a1779324b39f
Revises: 00c6dc6b54bb
Create Date: 2023-11-11 12:09:38.600378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1779324b39f"
down_revision: Union[str, None] = "00c6dc6b54bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction_row",
        sa.Column(
            "value_type",
            sa.Enum("CASH", "CREDIT", name="transactionvaluetype"),
            nullable=False,
        ),
    )
    op.add_column(
        "transaction_row",
        sa.Column(
            "reason",
            sa.Enum(
                "WALLET_CHARGING",
                "PROFIT",
                "PURCHASE",
                "FEE",
                "REGISTER",
                name="transactionreasonenum",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "transaction_row",
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "FAILED", "ACCEPTED", name="transactionstatusenum"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction_row", "status")
    op.drop_column("transaction_row", "reason")
    op.drop_column("transaction_row", "value_type")
    # ### end Alembic commands ###
