"""empty message

Revision ID: a3f88a3d23cf
Revises: 1665a15aaae2
Create Date: 2023-12-03 16:50:28.250471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3f88a3d23cf"
down_revision: Union[str, None] = "1665a15aaae2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_request", "father_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_request",
        sa.Column("father_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
