"""empty message

Revision ID: d719d6ffd50a
Revises: 7aae2728f222
Create Date: 2023-10-16 13:18:56.434461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d719d6ffd50a"
down_revision: Union[str, None] = "7aae2728f222"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "merchant",
        sa.Column(
            "field_of_work",
            sa.Enum(
                "MOBILE_STORE",
                "AUDIO_AND_VIDEO_PRODUCT_STORE",
                "KITCHEN_ACCESSORIES_STORE",
                "ELECTRICAL_APPLIANCES_STORE",
                "SLEEP_GOODS_STORES",
                "FURNITURE_STORES",
                "GROCERY_STORES",
                "PROTEIN_STORE",
                "CHANDELIERS_AND_ELECTRICAL_APPLIANCES",
                "SUPER_MARKETS",
                "BAKERY",
                "FRUIT_SHOPS",
                "STATIONERY_STORES",
                "DTY_FRUITS_SHOP",
                "DENTAL_CLINICS",
                "BEAUTY_CLINICS",
                "CLINICS",
                "CLOTHING_STORES",
                "HAIRDRESSERS",
                "LASER_CENTERS",
                "GOLD_AND_SILVER",
                "WATCH_SHOP",
                "PERFUME_AND_COLOGNE_STORE",
                "DECORATION",
                "COSMETIC",
                "MESON",
                "CAR_REPAIRS",
                "PHARMACY",
                "EDUCATIONAL_SERVICES",
                name="fieldofworktype",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merchant", "field_of_work")
    # ### end Alembic commands ###
