"""empty message

Revision ID: 67d2f57ec22d
Revises: 109e3ee0522d
Create Date: 2023-10-02 15:03:25.148573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d2f57ec22d'
down_revision: Union[str, None] = '109e3ee0522d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'agent', 'user', ['agent_user_id'], ['id'], use_alter=True)
    op.add_column('organization', sa.Column('profit_rate', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'organization', 'user', ['user_organization_id'], ['id'], use_alter=True)
    op.add_column('user', sa.Column('self_organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user', 'organization', ['self_organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'self_organization_id')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'profit_rate')
    op.drop_constraint(None, 'agent', type_='foreignkey')
    # ### end Alembic commands ###
