"""empty message

Revision ID: bbd4eb834e22
Revises: 31d568138d3f
Create Date: 2023-10-09 15:44:29.195648

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

from src.position_request.models import FieldOfWorkType

# revision identifiers, used by Alembic.
revision: str = "bbd4eb834e22"
down_revision: Union[str, None] = "31d568138d3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    field_of_work = postgresql.ENUM(FieldOfWorkType, name="fieldofworktype")
    field_of_work.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "position_request",
        sa.Column("field_of_work", field_of_work, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    field_of_work = postgresql.ENUM(FieldOfWorkType, name="fieldofworktype")
    field_of_work.drop(op.get_bind())
    op.drop_column("position_request", "field_of_work")
    # ### end Alembic commands ###
