"""empty message

Revision ID: 82c3f9850f1d
Revises: 1c759aa9ce5e
Create Date: 2023-10-01 18:36:22.246129

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82c3f9850f1d"
down_revision: Union[str, None] = "1c759aa9ce5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "agent",
        "user",
        ["agent_user_id"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        None,
        "organization",
        "user",
        ["user_organization_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organization", type_="foreignkey")
    op.drop_constraint(None, "agent", type_="foreignkey")
    # ### end Alembic commands ###
