"""empty message

Revision ID: 4ed0a2f3e6dd
Revises: b7e9bf7d4c7e
Create Date: 2023-12-06 12:55:21.557436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ed0a2f3e6dd"
down_revision: Union[str, None] = "b7e9bf7d4c7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "important_data",
        sa.Column("icart_members", sa.Integer(), nullable=True),
    )
    op.add_column(
        "important_data",
        sa.Column("referral_user_number", sa.Integer(), nullable=True),
    )
    op.add_column(
        "important_data",
        sa.Column("referral_transactions", sa.Integer(), nullable=True),
    )
    op.add_column(
        "important_data",
        sa.Column("referral_transaction_percentage", sa.Float(), nullable=True),
    )
    op.add_column(
        "important_data",
        sa.Column("referral_discount", sa.Integer(), nullable=True),
    )
    op.add_column(
        "important_data",
        sa.Column("referral_reward", sa.Integer(), nullable=True),
    )
    op.add_column("user", sa.Column("icart_member_number", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("referral_code", sa.String(), nullable=True))
    op.add_column(
        "user",
        sa.Column("referral_transactions", sa.Integer(), nullable=True),
    )
    op.add_column("user", sa.Column("referrer_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_user_referral_code"),
        "user",
        ["referral_code"],
        unique=True,
    )
    op.create_index(op.f("ix_user_referrer_id"), "user", ["referrer_id"], unique=False)
    op.create_foreign_key(None, "user", "user", ["referrer_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_index(op.f("ix_user_referrer_id"), table_name="user")
    op.drop_index(op.f("ix_user_referral_code"), table_name="user")
    op.drop_column("user", "referrer_id")
    op.drop_column("user", "referral_transactions")
    op.drop_column("user", "referral_code")
    op.drop_column("user", "icart_member_number")
    op.drop_column("important_data", "referral_reward")
    op.drop_column("important_data", "referral_discount")
    op.drop_column("important_data", "referral_transaction_percentage")
    op.drop_column("important_data", "referral_transactions")
    op.drop_column("important_data", "referral_user_number")
    op.drop_column("important_data", "icart_members")
    # ### end Alembic commands ###
