"""empty message

Revision ID: 7ec79e077e1a
Revises: 44bdeb676554
Create Date: 2023-10-03 23:49:21.340514

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ec79e077e1a"
down_revision: Union[str, None] = "44bdeb676554"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "capital_transfer",
        sa.Column("transaction_id", sa.UUID(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "capital_transfer",
        "capital_transfer",
        ["transaction_id"],
        ["id"],
    )
    op.drop_constraint(
        "transaction_capital_transfer_id_fkey",
        "transaction",
        type_="foreignkey",
    )
    op.drop_column("transaction", "capital_transfer_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column("capital_transfer_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "transaction_capital_transfer_id_fkey",
        "transaction",
        "capital_transfer",
        ["capital_transfer_id"],
        ["id"],
    )
    op.drop_constraint(None, "capital_transfer", type_="foreignkey")
    op.drop_column("capital_transfer", "transaction_id")
    # ### end Alembic commands ###
