"""empty message

Revision ID: 6e19d3832fd0
Revises: 3e35f3c34b78
Create Date: 2023-11-08 15:15:30.527874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e19d3832fd0"
down_revision: Union[str, None] = "3e35f3c34b78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallet", "credit_balance")
    op.drop_column("wallet", "cash_balance")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet",
        sa.Column("cash_balance", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "wallet",
        sa.Column("credit_balance", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
