"""empty message

Revision ID: d95b667e1afc
Revises: e8c9f63fd288
Create Date: 2023-10-04 14:51:35.879303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d95b667e1afc"
down_revision: Union[str, None] = "e8c9f63fd288"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("credit", sa.Column("paid", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credit", "paid")
    # ### end Alembic commands ###
