"""empty message

Revision ID: 6d2e5857cf6c
Revises: 7e919ca7fba4
Create Date: 2023-10-03 11:41:49.569441

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d2e5857cf6c"
down_revision: Union[str, None] = "7e919ca7fba4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organization", sa.Column("address", sa.TEXT(), nullable=True))
    op.add_column("organization", sa.Column("location_id", sa.UUID(), nullable=True))
    op.alter_column(
        "organization",
        "contract_number",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_index("ix_organization_contract_number", table_name="organization")
    op.create_foreign_key(None, "organization", "location", ["location_id"], ["id"])
    op.drop_index("ix_user_one_time_password", table_name="user")
    op.drop_column("user", "one_time_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "one_time_password",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        "ix_user_one_time_password",
        "user",
        ["one_time_password"],
        unique=False,
    )
    op.drop_constraint(None, "organization", type_="foreignkey")
    op.create_index(
        "ix_organization_contract_number",
        "organization",
        ["contract_number"],
        unique=False,
    )
    op.alter_column(
        "organization",
        "contract_number",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("organization", "location_id")
    op.drop_column("organization", "address")
    # ### end Alembic commands ###
