"""empty message

Revision ID: b68750c8bad9
Revises: 4eff597b5439
Create Date: 2023-09-30 13:24:33.851976

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b68750c8bad9"
down_revision: Union[str, None] = "4eff597b5439"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypto",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crypto_id"), "crypto", ["id"], unique=True)
    op.create_index(op.f("ix_crypto_name"), "crypto", ["name"], unique=True)
    op.create_table(
        "user_crypto",
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("wallet_id", sa.UUID(), nullable=True),
        sa.Column("crypto_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["crypto_id"],
            ["crypto.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_crypto_id"), "user_crypto", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_crypto_id"), table_name="user_crypto")
    op.drop_table("user_crypto")
    op.drop_index(op.f("ix_crypto_name"), table_name="crypto")
    op.drop_index(op.f("ix_crypto_id"), table_name="crypto")
    op.drop_table("crypto")
    # ### end Alembic commands ###
