"""empty message

Revision ID: 1eb4c183ef5a
Revises: cce06970a3fa
Create Date: 2023-10-11 08:43:08.977966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1eb4c183ef5a"
down_revision: Union[str, None] = "cce06970a3fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("code", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "code")
    # ### end Alembic commands ###
