"""empty message

Revision ID: e2bbedecb006
Revises: 65c00837dd66
Create Date: 2023-11-06 15:42:56.612748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2bbedecb006"
down_revision: Union[str, None] = "65c00837dd66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("merchant", sa.Column("geo", sa.String(), nullable=True))
    op.add_column("position_request", sa.Column("geo", sa.String(), nullable=True))
    op.execute("ALTER TYPE sellingtype ADD VALUE 'CASH_INSTALLMENT'")
    op.execute("ALTER TYPE sellingtype ADD VALUE 'CREDIT_INSTALLMENT'")
    op.execute("ALTER TYPE sellingtype RENAME VALUE 'BOTH' TO 'ALL_THREE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("position_request", "geo")
    op.drop_column("merchant", "geo")
    # ### end Alembic commands ###
