"""empty message

Revision ID: 423a2f4a8441
Revises: 7b23fa3cb199
Create Date: 2023-10-28 22:44:13.773297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "423a2f4a8441"
down_revision: Union[str, None] = "7b23fa3cb199"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("birth_place", sa.String(), nullable=True))
    op.add_column("user", sa.Column("postal_code", sa.String(), nullable=True))
    op.add_column("user", sa.Column("father_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("tel", sa.String(), nullable=True))
    op.add_column("user", sa.Column("address", sa.String(), nullable=True))
    op.add_column(
        "user",
        sa.Column("national_card_front_version_id", sa.String(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("national_card_front_name", sa.String(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("national_card_back_version_id", sa.String(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("national_card_back_name", sa.String(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("birth_certificate_version_id", sa.String(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("birth_certificate_name", sa.String(), nullable=True),
    )
    op.add_column("user", sa.Column("video_version_id", sa.String(), nullable=True))
    op.add_column("user", sa.Column("video_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "video_name")
    op.drop_column("user", "video_version_id")
    op.drop_column("user", "birth_certificate_name")
    op.drop_column("user", "birth_certificate_version_id")
    op.drop_column("user", "national_card_back_name")
    op.drop_column("user", "national_card_back_version_id")
    op.drop_column("user", "national_card_front_name")
    op.drop_column("user", "national_card_front_version_id")
    op.drop_column("user", "address")
    op.drop_column("user", "tel")
    op.drop_column("user", "father_name")
    op.drop_column("user", "postal_code")
    op.drop_column("user", "birth_place")
    # ### end Alembic commands ###
