"""empty message

Revision ID: e318f7bc552e
Revises: 8ad23b4733c8
Create Date: 2023-10-16 15:11:08.629011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e318f7bc552e"
down_revision: Union[str, None] = "8ad23b4733c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE sellingtype ADD VALUE 'INSTALLMENT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE sellingtype DROP VALUE 'INSTALLMENT'")
    # ### end Alembic commands ###
