"""empty message

Revision ID: 642166ff09ca
Revises: b3ba9bf81b8e
Create Date: 2023-11-25 13:19:48.809975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "642166ff09ca"
down_revision: Union[str, None] = "b3ba9bf81b8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_deposit_id", table_name="deposit")
    op.drop_index("ix_deposit_wallet_id", table_name="deposit")
    op.drop_table("deposit")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposit",
        sa.Column("amount", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("zibal_track_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("wallet_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["bank_card.id"],
            name="deposit_wallet_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="deposit_pkey"),
    )
    op.create_index("ix_deposit_wallet_id", "deposit", ["wallet_id"], unique=False)
    op.create_index("ix_deposit_id", "deposit", ["id"], unique=False)
    # ### end Alembic commands ###
