"""empty message

Revision ID: d9b3c95beb59
Revises: eace3470af87
Create Date: 2023-11-24 14:13:01.295506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9b3c95beb59"
down_revision: Union[str, None] = "eace3470af87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("card", sa.Column("is_receive", sa.Boolean(), nullable=True))
    op.execute("ALTER TYPE logtype ADD VALUE 'CREATE_ABILITY'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("card", "is_receive")
    # ### end Alembic commands ###
