"""empty message

Revision ID: 257d8c6a0b61
Revises: d870966a926b
Create Date: 2023-11-11 15:20:50.967418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "257d8c6a0b61"
down_revision: Union[str, None] = "d870966a926b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("value", sa.Float(), nullable=False))
    op.add_column(
        "transaction",
        sa.Column(
            "value_type",
            sa.Enum("CASH", "CREDIT", name="transactionvaluetype"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "value_type")
    op.drop_column("transaction", "value")
    # ### end Alembic commands ###
