"""empty message

Revision ID: f47960149d91
Revises: a6dc0607e4eb
Create Date: 2023-10-04 22:06:12.913243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f47960149d91"
down_revision: Union[str, None] = "a6dc0607e4eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cash",
        sa.Column("received", sa.Integer(), nullable=True),
        sa.Column("paid", sa.Integer(), nullable=True),
        sa.Column("consumed", sa.Integer(), nullable=True),
        sa.Column("remaining", sa.Integer(), nullable=True),
        sa.Column("transferred", sa.Integer(), nullable=True),
        sa.Column("debt", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cash_id"), "cash", ["id"], unique=True)
    op.add_column("user", sa.Column("cash_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "user", "cash", ["cash_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "cash_id")
    op.drop_index(op.f("ix_cash_id"), table_name="cash")
    op.drop_table("cash")
    # ### end Alembic commands ###
