"""empty message

Revision ID: d9a2322d8faf
Revises: ae5ddd885f25
Create Date: 2023-10-14 10:54:23.473709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.capital_transfer.models import CapitalTransferStatusEnum

# revision identifiers, used by Alembic.
revision: str = "d9a2322d8faf"
down_revision: Union[str, None] = "ae5ddd885f25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    capital_transfer_status = postgresql.ENUM(
        CapitalTransferStatusEnum,
        name="capitaltransferstatusenum",
    )
    capital_transfer_status.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "capital_transfer",
        sa.Column("status", capital_transfer_status, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("capital_transfer", "status")
    capital_transfer_status = postgresql.ENUM(
        CapitalTransferStatusEnum,
        name="capitaltransferstatusenum",
    )
    capital_transfer_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
