"""empty message

Revision ID: b92c7b53be83
Revises: 751be9ad62fe
Create Date: 2023-10-08 09:20:42.478463

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b92c7b53be83"
down_revision: Union[str, None] = "751be9ad62fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
