"""empty message

Revision ID: 44bdeb676554
Revises: b5520d62098d
Create Date: 2023-10-03 23:46:15.225584

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44bdeb676554"
down_revision: Union[str, None] = "b5520d62098d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column("capital_transfer_id", sa.UUID(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "transaction",
        "capital_transfer",
        ["capital_transfer_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.drop_column("transaction", "capital_transfer_id")
    # ### end Alembic commands ###
