"""empty message

Revision ID: efa723d083f5
Revises: 3773dd658959
Create Date: 2023-09-30 10:59:18.225952

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "efa723d083f5"
down_revision: Union[str, None] = "3773dd658959"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
