"""empty message

Revision ID: 57931035b080
Revises: 1750d7c8eced
Create Date: 2023-11-12 15:36:42.590312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "57931035b080"
down_revision: Union[str, None] = "1750d7c8eced"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("code", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "transaction", ["code"])
    op.add_column("transaction_row", sa.Column("code", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "transaction_row", ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction_row", type_="unique")
    op.drop_column("transaction_row", "code")
    op.drop_constraint(None, "transaction", type_="unique")
    op.drop_column("transaction", "code")
    # ### end Alembic commands ###
