"""empty message

Revision ID: b40178469cd7
Revises: c59f5c3d03a3
Create Date: 2023-11-04 12:50:58.899513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b40178469cd7"
down_revision: Union[str, None] = "c59f5c3d03a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
