"""empty message

Revision ID: bd2eb8cee337
Revises: ec0eb262872d
Create Date: 2023-11-10 03:43:56.859971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bd2eb8cee337"
down_revision: Union[str, None] = "ec0eb262872d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position_request_ability",
        sa.Column("position_request_id", sa.UUID(), nullable=True),
        sa.Column("ability_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["ability_id"], ["ability.id"]),
        sa.ForeignKeyConstraint(["position_request_id"], ["position_request.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("ALTER TYPE positionrequesttype ADD VALUE 'SALES_AGENT'")

    op.create_index(
        op.f("ix_position_request_ability_id"),
        "position_request_ability",
        ["id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction",
        "status",
        existing_type=postgresql.ENUM(
            "IN_PROGRESS",
            "FAILED",
            "ACCEPTED",
            name="transactionstatusenum",
        ),
        nullable=True,
    )
    op.drop_index(
        op.f("ix_position_request_ability_id"),
        table_name="position_request_ability",
    )
    op.drop_table("position_request_ability")
    # ### end Alembic commands ###
