"""empty message

Revision ID: 1e30189f95a6
Revises: 0a59f5e3a05e
Create Date: 2023-10-01 12:17:58.018219

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1e30189f95a6"
down_revision: Union[str, None] = "0a59f5e3a05e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
