"""empty message

Revision ID: eace3470af87
Revises: 463e73a18aaf
Create Date: 2023-11-24 10:23:32.698237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eace3470af87"
down_revision: Union[str, None] = "463e73a18aaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_card",
        sa.Column("card_number", sa.String(), nullable=True),
        sa.Column("shaba_number", sa.String(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bank_card_card_number"),
        "bank_card",
        ["card_number"],
        unique=True,
    )
    op.create_index(op.f("ix_bank_card_id"), "bank_card", ["id"], unique=True)
    op.create_index(
        op.f("ix_bank_card_shaba_number"),
        "bank_card",
        ["shaba_number"],
        unique=True,
    )
    op.create_table(
        "withdraw",
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("is_done", sa.Boolean(), nullable=True),
        sa.Column("bank_card_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["bank_card_id"], ["bank_card.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_withdraw_bank_card_id"),
        "withdraw",
        ["bank_card_id"],
        unique=False,
    )
    op.create_index(op.f("ix_withdraw_id"), "withdraw", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_withdraw_id"), table_name="withdraw")
    op.drop_index(op.f("ix_withdraw_bank_card_id"), table_name="withdraw")
    op.drop_table("withdraw")
    op.drop_index(op.f("ix_bank_card_shaba_number"), table_name="bank_card")
    op.drop_index(op.f("ix_bank_card_id"), table_name="bank_card")
    op.drop_index(op.f("ix_bank_card_card_number"), table_name="bank_card")
    op.drop_table("bank_card")
    # ### end Alembic commands ###
