"""empty message

Revision ID: b619fba73407
Revises: c6b56dd7c4ec
Create Date: 2023-10-10 22:38:21.884778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.position_request.models import FieldOfWorkType

# revision identifiers, used by Alembic.
revision: str = "b619fba73407"
down_revision: Union[str, None] = "c6b56dd7c4ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    field_of_work = postgresql.ENUM(FieldOfWorkType, name="fieldofworktype")
    field_of_work.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        "position_request",
        "field_of_work",
        type_=postgresql.BIT(varying=True),
        postgresql_using="field_of_work::fieldofworktype",
    )

    # op.alter_column(
    #     "position_request",
    #     "field_of_work",
    #     existing_type=postgresql.ENUM(
    #         "FORGET_PASSWORD",
    #         "REGISTER",
    #         name="verifyphonetype",
    #     ),
    #     type_=sa.Enum(
    #         "MOBILE_STORE",
    #         "AUDIO_AND_VIDEO_PRODUCT_STORE",
    #         "KITCHEN_ACCESSORIES_STORE",
    #         "ELECTRICAL_APPLIANCES_STORE",
    #         "SLEEP_GOODS_STORES",
    #         "FURNITURE_STORES",
    #         "GROCERY_STORES",
    #         "PROTEIN_STORE",
    #         "CHANDELIERS_AND_ELECTRICAL_APPLIANCES",
    #         "SUPER_MARKETS",
    #         "BAKERY",
    #         "FRUIT_SHOPS",
    #         "STATIONERY_STORES",
    #         "DTY_FRUITS_SHOP",
    #         "DENTAL_CLINICS",
    #         "BEAUTY_CLINICS",
    #         "CLINICS",
    #         "CLOTHING_STORES",
    #         "HAIRDRESSERS",
    #         "LASER_CENTERS",
    #         "GOLD_AND_SILVER",
    #         "WATCH_SHOP",
    #         "PERFUME_AND_COLOGNE_STORE",
    #         "DECORATION",
    #         "COSMETIC",
    #         "MESON",
    #         "CAR_REPAIRS",
    #         "PHARMACY",
    #         "EDUCATIONAL_SERVICES",
    #         name="fieldofworktype",
    #     ),
    #     existing_nullable=True,
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "position_request",
        "field_of_work",
        existing_type=sa.Enum(
            "MOBILE_STORE",
            "AUDIO_AND_VIDEO_PRODUCT_STORE",
            "KITCHEN_ACCESSORIES_STORE",
            "ELECTRICAL_APPLIANCES_STORE",
            "SLEEP_GOODS_STORES",
            "FURNITURE_STORES",
            "GROCERY_STORES",
            "PROTEIN_STORE",
            "CHANDELIERS_AND_ELECTRICAL_APPLIANCES",
            "SUPER_MARKETS",
            "BAKERY",
            "FRUIT_SHOPS",
            "STATIONERY_STORES",
            "DTY_FRUITS_SHOP",
            "DENTAL_CLINICS",
            "BEAUTY_CLINICS",
            "CLINICS",
            "CLOTHING_STORES",
            "HAIRDRESSERS",
            "LASER_CENTERS",
            "GOLD_AND_SILVER",
            "WATCH_SHOP",
            "PERFUME_AND_COLOGNE_STORE",
            "DECORATION",
            "COSMETIC",
            "MESON",
            "CAR_REPAIRS",
            "PHARMACY",
            "EDUCATIONAL_SERVICES",
            name="fieldofworktype",
        ),
        type_=postgresql.ENUM("FORGET_PASSWORD", "REGISTER", name="verifyphonetype"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
