"""empty message

Revision ID: 8b7ca9675f80
Revises: 997b523882da
Create Date: 2023-09-30 14:57:14.599930

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b7ca9675f80"
down_revision: Union[str, None] = "997b523882da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ticket", sa.Column("number", sa.Integer(), nullable=False))
    op.drop_index("ix_ticket_code", table_name="ticket")
    op.create_index(op.f("ix_ticket_number"), "ticket", ["number"], unique=True)
    op.drop_column("ticket", "code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ticket",
        sa.Column("code", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_ticket_number"), table_name="ticket")
    op.create_index("ix_ticket_code", "ticket", ["code"], unique=False)
    op.drop_column("ticket", "number")
    # ### end Alembic commands ###
