"""empty message

Revision ID: 4eff597b5439
Revises: efa723d083f5
Create Date: 2023-09-30 11:05:27.015817

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4eff597b5439"
down_revision: Union[str, None] = "efa723d083f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
