"""empty message

Revision ID: 6f1769bfceec
Revises: d719d6ffd50a
Create Date: 2023-10-16 14:33:03.814490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.position_request.models import SellingType

# revision identifiers, used by Alembic.
revision: str = "6f1769bfceec"
down_revision: Union[str, None] = "d719d6ffd50a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    selling_type = postgresql.ENUM(
        SellingType,
        name="sellingtype",
    )
    selling_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "position_request",
        sa.Column("selling_type", selling_type, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("position_request", "selling_type")
    selling_type = postgresql.ENUM(
        SellingType,
        name="sellingtype",
    )
    selling_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
