"""empty message

Revision ID: 31d568138d3f
Revises: ef98f1780aea
Create Date: 2023-10-09 15:44:08.277163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31d568138d3f"
down_revision: Union[str, None] = "ef98f1780aea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_position_request_number", table_name="position_request")
    op.drop_column("position_request", "number")
    op.create_index(
        op.f("ix_user_message_title"),
        "user_message",
        ["title"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_message_title"), table_name="user_message")
    op.add_column(
        "position_request",
        sa.Column("number", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_index(
        "ix_position_request_number",
        "position_request",
        ["number"],
        unique=False,
    )
    # ### end Alembic commands ###
