"""empty message

Revision ID: 0a59f5e3a05e
Revises: 146eaf81058f
Create Date: 2023-10-01 10:09:43.522380

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0a59f5e3a05e"
down_revision: Union[str, None] = "146eaf81058f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    post_status = postgresql.ENUM("CASH", "CREDIT", name="transactionvaluetype")
    post_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transaction2_id", table_name="transaction2")
    op.drop_table("transaction2")
    op.add_column("transaction", sa.Column("text", sa.String(), nullable=False))
    op.add_column(
        "transaction",
        sa.Column(
            "value_type",
            sa.Enum("CASH", "CREDIT", name="transactionvaluetype"),
            nullable=False,
        ),
    )
    op.drop_constraint("transaction_invoice_id_fkey", "transaction", type_="foreignkey")
    op.drop_column("transaction", "invoice_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    post_status = postgresql.ENUM("CASH", "CREDIT", name="transactionvaluetype")
    post_status.drop(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column("invoice_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "transaction_invoice_id_fkey",
        "transaction",
        "invoice",
        ["invoice_id"],
        ["id"],
    )
    op.drop_column("transaction", "value_type")
    op.drop_column("transaction", "text")
    op.create_table(
        "transaction2",
        sa.Column(
            "type",
            postgresql.ENUM("aaa", name="transactionreasonenum22"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "type2",
            postgresql.ENUM("aaa", name="transactionreasonenum33"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="transaction2_pkey"),
    )
    op.create_index("ix_transaction2_id", "transaction2", ["id"], unique=False)
    # ### end Alembic commands ###
