"""empty message

Revision ID: 78a2a128cb1e
Revises: 7ec79e077e1a
Create Date: 2023-10-04 00:26:47.522230

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78a2a128cb1e"
down_revision: Union[str, None] = "7ec79e077e1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "capital_transfer_transaction_id_fkey",
        "capital_transfer",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "capital_transfer",
        "transaction",
        ["transaction_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "capital_transfer", type_="foreignkey")
    op.create_foreign_key(
        "capital_transfer_transaction_id_fkey",
        "capital_transfer",
        "capital_transfer",
        ["transaction_id"],
        ["id"],
    )
    # ### end Alembic commands ###
