"""empty message

Revision ID: 9590b805e60b
Revises: 1740b36d6c06
Create Date: 2023-11-11 13:25:43.795677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9590b805e60b"
down_revision: Union[str, None] = "1740b36d6c06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("intermediary_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "transaction", "wallet", ["intermediary_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column("transaction", "intermediary_id")
    # ### end Alembic commands ###
