"""empty message

Revision ID: c513d192fe14
Revises: e023e7d9ce3c
Create Date: 2023-10-08 09:48:19.503220

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c513d192fe14"
down_revision: Union[str, None] = "e023e7d9ce3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
