"""empty message

Revision ID: c6b56dd7c4ec
Revises: 31d568138d3f
Create Date: 2023-10-10 22:34:40.933207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.position_request.models import FieldOfWorkType

# revision identifiers, used by Alembic.
revision: str = "c6b56dd7c4ec"
down_revision: Union[str, None] = "31d568138d3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pos", sa.Column("number", sa.String(), nullable=True))
    op.drop_index("ix_pos_token", table_name="pos")
    op.create_index(op.f("ix_pos_number"), "pos", ["number"], unique=True)
    op.drop_column("pos", "token")


1  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("position_request", "field_of_work")
    op.add_column(
        "pos",
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_pos_number"), table_name="pos")
    op.create_index("ix_pos_token", "pos", ["token"], unique=False)
    op.drop_column("pos", "number")
    # ### end Alembic commands ###
