"""empty message

Revision ID: af4bc89f5c3c
Revises: 1ded7222dca9
Create Date: 2023-11-13 07:47:48.571370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af4bc89f5c3c"
down_revision: Union[str, None] = "1ded7222dca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wallet", sa.Column("is_lock", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallet", "is_lock")
    # ### end Alembic commands ###
