"""empty message

Revision ID: 7e919ca7fba4
Revises: 80edd634af0b
Create Date: 2023-10-03 03:09:45.986838

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e919ca7fba4"
down_revision: Union[str, None] = "80edd634af0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization",
        "contract_number",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.create_index(
        op.f("ix_organization_contract_number"),
        "organization",
        ["contract_number"],
        unique=False,
    )
    op.drop_constraint(
        "organization_location_id_fkey",
        "organization",
        type_="foreignkey",
    )
    op.drop_column("organization", "address")
    op.drop_column("organization", "location_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("location_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "organization_location_id_fkey",
        "organization",
        "location",
        ["location_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_organization_contract_number"), table_name="organization")
    op.alter_column(
        "organization",
        "contract_number",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###
