"""empty message

Revision ID: cdcbed639033
Revises: 16d45dfb2584
Create Date: 2023-11-19 10:19:36.797905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cdcbed639033"
down_revision: Union[str, None] = "16d45dfb2584"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("credit", sa.Column("credit_back", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credit", "credit_back")
    # ### end Alembic commands ###
