"""empty message

Revision ID: 6b0c46d43fc1
Revises: f9f0e04cd3d1
Create Date: 2023-10-04 03:36:39.882824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b0c46d43fc1"
down_revision: Union[str, None] = "f9f0e04cd3d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "agent", "agent", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "agent", type_="foreignkey")
    op.drop_column("agent", "parent_id")
    # ### end Alembic commands ###
