"""empty message

Revision ID: 718d67ef2976
Revises: d9a2322d8faf
Create Date: 2023-10-14 11:21:24.560157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.transaction.models import TransactionReasonEnum

# revision identifiers, used by Alembic.
revision: str = "718d67ef2976"
down_revision: Union[str, None] = "d9a2322d8faf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    transaction_reason = postgresql.ENUM(
        TransactionReasonEnum,
        name="transactionreasonenum",
    )
    transaction_reason.create(op.get_bind(), checkfirst=True)
    op.add_column("transaction", sa.Column("reason", transaction_reason, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "reason")
    transaction_reason = postgresql.ENUM(
        TransactionReasonEnum,
        name="transactionreasonenum",
    )
    transaction_reason.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
