"""empty message

Revision ID: 21c5edeff16e
Revises: d5b34299548e
Create Date: 2023-11-24 18:27:34.585742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21c5edeff16e"
down_revision: Union[str, None] = "d5b34299548e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE logtype ADD VALUE 'CREATE_ABILITY'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
