"""empty message

Revision ID: ae5ddd885f25
Revises: bf3429f91a9a
Create Date: 2023-10-11 09:16:23.925313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae5ddd885f25"
down_revision: Union[str, None] = "bf3429f91a9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "position_request",
        sa.Column(
            "field_of_work",
            sa.Enum(
                "MOBILE_STORE",
                "AUDIO_AND_VIDEO_PRODUCT_STORE",
                "KITCHEN_ACCESSORIES_STORE",
                "ELECTRICAL_APPLIANCES_STORE",
                "SLEEP_GOODS_STORES",
                "FURNITURE_STORES",
                "GROCERY_STORES",
                "PROTEIN_STORE",
                "CHANDELIERS_AND_ELECTRICAL_APPLIANCES",
                "SUPER_MARKETS",
                "BAKERY",
                "FRUIT_SHOPS",
                "STATIONERY_STORES",
                "DTY_FRUITS_SHOP",
                "DENTAL_CLINICS",
                "BEAUTY_CLINICS",
                "CLINICS",
                "CLOTHING_STORES",
                "HAIRDRESSERS",
                "LASER_CENTERS",
                "GOLD_AND_SILVER",
                "WATCH_SHOP",
                "PERFUME_AND_COLOGNE_STORE",
                "DECORATION",
                "COSMETIC",
                "MESON",
                "CAR_REPAIRS",
                "PHARMACY",
                "EDUCATIONAL_SERVICES",
                name="fieldofworktype",
            ),
            nullable=True,
        ),
    )
    op.drop_column("position_request", "fields_of_work")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "position_request",
        sa.Column(
            "fields_of_work",
            postgresql.ENUM(
                "MOBILE_STORE",
                "AUDIO_AND_VIDEO_PRODUCT_STORE",
                "KITCHEN_ACCESSORIES_STORE",
                "ELECTRICAL_APPLIANCES_STORE",
                "SLEEP_GOODS_STORES",
                "FURNITURE_STORES",
                "GROCERY_STORES",
                "PROTEIN_STORE",
                "CHANDELIERS_AND_ELECTRICAL_APPLIANCES",
                "SUPER_MARKETS",
                "BAKERY",
                "FRUIT_SHOPS",
                "STATIONERY_STORES",
                "DTY_FRUITS_SHOP",
                "DENTAL_CLINICS",
                "BEAUTY_CLINICS",
                "CLINICS",
                "CLOTHING_STORES",
                "HAIRDRESSERS",
                "LASER_CENTERS",
                "GOLD_AND_SILVER",
                "WATCH_SHOP",
                "PERFUME_AND_COLOGNE_STORE",
                "DECORATION",
                "COSMETIC",
                "MESON",
                "CAR_REPAIRS",
                "PHARMACY",
                "EDUCATIONAL_SERVICES",
                name="fieldofworktype",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("position_request", "field_of_work")
    # ### end Alembic commands ###
