"""empty message

Revision ID: b40178469cd7
Revises: c59f5c3d03a3
Create Date: 2023-11-04 12:50:58.899513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b40178469cd7"
down_revision: Union[str, None] = "c59f5c3d03a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'MOBILE_STORE' TO 'HAIR_TRANSPLANT'")
    # op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'AUDIO_AND_VIDEO_PRODUCT_STORE' TO 'BEAUTY_CLINICS'")
    # op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'KITCHEN_ACCESSORIES_STORE' TO 'DENTAL_CLINICS'")
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'FURNITURE_STORES' TO 'FACIAL_GEL_BOTOX'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'GROCERY_STORES' TO 'FURNITURE_STORES'",
    )
    # op.execute("ALTER TYPE fieldofworktype ADD VALUE 'PROTEIN_STORE'")
    # op.execute("ALTER TYPE fieldofworktype ADD VALUE 'CHANDELIERS_AND_ELECTRICAL_APPLIANCES'")
    op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'SUPER_MARKETS' TO 'CARPET'")
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'BAKERY' TO 'ELECTRICAL_APPLIANCES_REPAIRS'",
    )
    op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'FRUIT_SHOPS' TO 'LAPTOP'")
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'STATIONERY_STORES' TO 'MOBILE'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'DTY_FRUITS_SHOP' TO 'DIGITAL_ACCESSORIES'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'DENTAL_CLINICS' TO 'TRAVEL_AGENCY'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'BEAUTY_CLINICS' TO 'RECREATIONAL_SPORTS_CENTERS'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'CLINICS' TO 'LANGUAGE_TEACHING'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'CLOTHING_STORES' TO 'HAIRDRESSING_TRAINING'",
    )
    op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'HAIRDRESSERS' TO 'STATIONERY'")
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'LASER_CENTERS' TO 'WATCH_GALLERY'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'GOLD_AND_SILVER' TO 'GOLD_SALES'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'WATCH_SHOP' TO 'JEWELRY_ACCESSORIES'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'PERFUME_AND_COLOGNE_STORE' TO 'SUPER_MARKET'",
    )
    op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'DECORATION' TO 'FRUIT_SHOP'")
    op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'COSMETIC' TO 'DAIRY'")
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'MESON' TO 'CAFE_RESTAURANT_FAST_FOOD'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'CAR_REPAIRS' TO 'CONFECTIONERY_DRIED_FRUIT'",
    )
    op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'PHARMACY' TO 'ASIA_INSURANCE'")
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'EDUCATIONAL_SERVICES' TO 'THIRD_PARTY_INSURANCE'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'HOME_APPLIANCES' TO 'ADULT_CLOTHING'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'TRANSPORTATION' TO 'CHILDREN_CLOTHING'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype ADD VALUE 'BAGS_AND_SHOES'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'RESTAURANT' TO 'INTERIOR_DECORATION_DESIGNER'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype ADD VALUE 'BUILDING_EQUIPMENT'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'ELECTRICAL_APPLIANCES_REPAIRS' TO 'BAKERY'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'DENTAL_CLINICS' TO 'KITCHEN_ACCESSORIES_STORE'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'HAIR_TRANSPLANT' TO 'MOBILE_STORE'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'BEAUTY_CLINICS' TO 'AUDIO_AND_VIDEO_PRODUCT_STORE'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'FACIAL_GEL_BOTOX' TO 'FURNITURE_STORES'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'FURNITURE_STORES' TO 'GROCERY_STORES'",
    )
    op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'LAPTOP' TO 'FRUIT_SHOPS'")
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'MOBILE' TO 'STATIONERY_STORES'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'DIGITAL_ACCESSORIES' TO 'DTY_FRUITS_SHOP'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'TRAVEL_AGENCY' TO 'DENTAL_CLINICS'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'RECREATIONAL_SPORTS_CENTERS' TO 'BEAUTY_CLINICS'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'LANGUAGE_TEACHING' TO 'CLINICS'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'HAIRDRESSING_TRAINING' TO 'CLOTHING_STORES'",
    )
    op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'STATIONERY' TO 'HAIRDRESSERS'")
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'WATCH_GALLERY' TO 'LASER_CENTERS'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'GOLD_SALES' TO 'GOLD_AND_SILVER'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'JEWELRY_ACCESSORIES' TO 'WATCH_SHOP'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'SUPER_MARKET' TO 'PERFUME_AND_COLOGNE_STORE'",
    )
    op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'FRUIT_SHOP' TO 'DECORATION'")
    op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'DAIRY' TO 'COSMETIC'")
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'CAFE_RESTAURANT_FAST_FOOD' TO 'MESON'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'CONFECTIONERY_DRIED_FRUIT' TO 'CAR_REPAIRS'",
    )
    op.execute("ALTER TYPE fieldofworktype RENAME VALUE 'ASIA_INSURANCE' TO 'PHARMACY'")
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'THIRD_PARTY_INSURANCE' TO 'EDUCATIONAL_SERVICES'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'ADULT_CLOTHING' TO 'HOME_APPLIANCES'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'CHILDREN_CLOTHING' TO 'TRANSPORTATION'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'BAGS_AND_SHOES' TO 'CONFECTIONARY'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'INTERIOR_DECORATION_DESIGNER' TO 'RESTAURANT'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'BUILDING_EQUIPMENT' TO 'HAIR_TRANSPLANT'",
    )
