"""empty message

Revision ID: e658a80517f1
Revises: db9ca1f73b61
Create Date: 2023-10-04 14:06:13.157495

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e658a80517f1"
down_revision: Union[str, None] = "db9ca1f73b61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
