"""empty message

Revision ID: 997b523882da
Revises: a27406966f95
Create Date: 2023-09-30 14:55:43.243104

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "997b523882da"
down_revision: Union[str, None] = "a27406966f95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ticket", sa.Column("importance", sa.Integer(), nullable=True))
    op.add_column("ticket", sa.Column("code", sa.Integer(), nullable=False))
    op.drop_index("ix_ticket_number", table_name="ticket")
    op.create_index(op.f("ix_ticket_code"), "ticket", ["code"], unique=True)
    op.drop_column("ticket", "number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ticket",
        sa.Column("number", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_ticket_code"), table_name="ticket")
    op.create_index("ix_ticket_number", "ticket", ["number"], unique=False)
    op.drop_column("ticket", "code")
    op.drop_column("ticket", "importance")
    # ### end Alembic commands ###
