"""empty message

Revision ID: d870966a926b
Revises: 262ca1e08a86
Create Date: 2023-11-11 15:01:58.723994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d870966a926b"
down_revision: Union[str, None] = "262ca1e08a86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "value")
    op.drop_column("transaction", "value_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column(
            "value_type",
            postgresql.ENUM("CASH", "CREDIT", name="transactionvaluetype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "transaction",
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
