"""empty message

Revision ID: 3701b4111554
Revises: ce247da3f143
Create Date: 2023-11-13 06:01:59.615169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3701b4111554"
down_revision: Union[str, None] = "ce247da3f143"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("merchant", sa.Column("profit_rate", sa.Integer(), nullable=True))
    op.add_column(
        "position_request",
        sa.Column("profit_rate", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("position_request", "profit_rate")
    op.drop_column("merchant", "profit_rate")
    # ### end Alembic commands ###
