"""empty message

Revision ID: 41dbafc80bb0
Revises: e6e3ac8b43fd
Create Date: 2023-10-05 11:46:26.646820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41dbafc80bb0"
down_revision: Union[str, None] = "e6e3ac8b43fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("image_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "image_name")
    # ### end Alembic commands ###
