"""empty message

Revision ID: c7ddb0564cc6
Revises: 1a7f9c2bde97
Create Date: 2023-11-10 05:01:55.410186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c7ddb0564cc6"
down_revision: Union[str, None] = "1a7f9c2bde97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fee",
        "user_type",
        existing_type=postgresql.ENUM("USER", "MERCHANT", name="feeusertype"),
        nullable=False,
    )
    op.drop_column("fee", "value_limit")
    op.alter_column(
        "transaction",
        "status",
        existing_type=postgresql.ENUM(
            "IN_PROGRESS",
            "FAILED",
            "ACCEPTED",
            name="transactionstatusenum",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction",
        "status",
        existing_type=postgresql.ENUM(
            "IN_PROGRESS",
            "FAILED",
            "ACCEPTED",
            name="transactionstatusenum",
        ),
        nullable=True,
    )
    op.add_column(
        "fee",
        sa.Column("value_limit", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "fee",
        "user_type",
        existing_type=postgresql.ENUM("USER", "MERCHANT", name="feeusertype"),
        nullable=True,
    )
    # ### end Alembic commands ###
