"""empty message

Revision ID: fb198cb729f9
Revises: 8b7ca9675f80
Create Date: 2023-09-30 15:04:26.724187

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fb198cb729f9"
down_revision: Union[str, None] = "8b7ca9675f80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
