"""empty message

Revision ID: db9ca1f73b61
Revises: 547263f0c1b8
Create Date: 2023-10-04 14:05:55.894518

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "db9ca1f73b61"
down_revision: Union[str, None] = "547263f0c1b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
