"""empty message

Revision ID: 0c9a29ed8cf0
Revises: 6d180ec479c3
Create Date: 2023-09-30 01:28:07.061805

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0c9a29ed8cf0"
down_revision: Union[str, None] = "6d180ec479c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("news", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("news", "text", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("permission", "code", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("ticket", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "ticket",
        "type",
        existing_type=postgresql.ENUM("TECHNICAL", "SALES", name="tickettype"),
        nullable=False,
    )
    op.add_column("user", sa.Column("location_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "user", "location", ["location_id"], ["id"])
    op.alter_column(
        "verify_phone",
        "phone_number",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "verify_phone",
        "verify_code",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "verify_phone",
        "expiration_code_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "verify_phone",
        "expiration_code_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "verify_phone",
        "verify_code",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "verify_phone",
        "phone_number",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "location_id")
    op.alter_column(
        "ticket",
        "type",
        existing_type=postgresql.ENUM("TECHNICAL", "SALES", name="tickettype"),
        nullable=True,
    )
    op.alter_column("ticket", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("permission", "code", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("news", "text", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("news", "title", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
