"""empty message

Revision ID: e023e7d9ce3c
Revises: b92c7b53be83
Create Date: 2023-10-08 09:24:33.056588

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e023e7d9ce3c"
down_revision: Union[str, None] = "b92c7b53be83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tickettype ADD VALUE 'ORGANIZATION'")
    op.execute("ALTER TYPE tickettype ADD VALUE 'MERCHANT'")
    op.execute("ALTER TYPE tickettype ADD VALUE 'AGENT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tickettype DELETE VALUE 'ORGANIZATION'")
    op.execute("ALTER TYPE tickettype DELETE VALUE 'MERCHANT'")
    op.execute("ALTER TYPE tickettype DELETE VALUE 'AGENT'")
    # ### end Alembic commands ###
