"""empty message

Revision ID: 1750d7c8eced
Revises: a12a3fea0baa
Create Date: 2023-11-12 15:36:27.335982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1750d7c8eced"
down_revision: Union[str, None] = "a12a3fea0baa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "code")
    op.drop_column("transaction_row", "code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction_row",
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "transaction",
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
