"""empty message

Revision ID: 6f9890642b62
Revises: ec52d57cb423
Create Date: 2023-10-18 16:23:20.129078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f9890642b62"
down_revision: Union[str, None] = "ec52d57cb423"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "installments_invoice_id_fkey",
        "installments",
        type_="foreignkey",
    )
    op.drop_column("installments", "invoice_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "installments",
        sa.Column("invoice_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "installments_invoice_id_fkey",
        "installments",
        "invoice",
        ["invoice_id"],
        ["id"],
    )
    # ### end Alembic commands ###
