"""empty message

Revision ID: 5e0b3d958225
Revises: e3b18f039d95
Create Date: 2023-12-02 10:09:41.032748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e0b3d958225"
down_revision: Union[str, None] = "e3b18f039d95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("position_request", sa.Column("detail", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("position_request", "detail")
    # ### end Alembic commands ###
