"""empty message

Revision ID: b7e9bf7d4c7e
Revises: a3f88a3d23cf
Create Date: 2023-12-05 22:30:36.085699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7e9bf7d4c7e"
down_revision: Union[str, None] = "a3f88a3d23cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
