"""empty message

Revision ID: 80edd634af0b
Revises: 2c8654e46dc3
Create Date: 2023-10-03 00:39:04.394580

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80edd634af0b"
down_revision: Union[str, None] = "2c8654e46dc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE wallet ALTER COLUMN number TYPE INTEGER USING number::integer",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.alter_column(
        "wallet",
        "number",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
