"""empty message

Revision ID: 378bbf23cf32
Revises: 57931035b080
Create Date: 2023-11-12 16:08:46.750905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "378bbf23cf32"
down_revision: Union[str, None] = "57931035b080"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "important_data",
        sa.Column("blue_card_cost", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("important_data", "blue_card_cost")
    # ### end Alembic commands ###
