"""empty message

Revision ID: c7d83c3cd812
Revises: 5e0b3d958225
Create Date: 2023-12-02 14:50:08.010702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7d83c3cd812"
down_revision: Union[str, None] = "5e0b3d958225"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_request", sa.Column("detail", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_request", "detail")
    # ### end Alembic commands ###
