"""empty message

Revision ID: 259ee738b404
Revises: f640bd60498c
Create Date: 2023-10-24 23:28:20.375765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "259ee738b404"
down_revision: Union[str, None] = "f640bd60498c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "position_request",
        sa.Column("received_money", sa.String(), nullable=True),
    )
    op.add_column(
        "position_request",
        sa.Column("tracking_code", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("position_request", "tracking_code")
    op.drop_column("position_request", "received_money")
    # ### end Alembic commands ###
