"""empty message

Revision ID: 885e71d08647
Revises: be6775000d50
Create Date: 2023-11-20 16:35:47.894160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "885e71d08647"
down_revision: Union[str, None] = "be6775000d50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("ALTER TYPE transactionstatusenum ADD VALUE 'IN_PROGRESS'")
    op.execute("ALTER TYPE logtype ADD VALUE 'CHARGING_CARD'")
    op.add_column(
        "transaction_row",
        sa.Column("zibal_track_id", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction_row", "zibal_track_id")
    # ### end Alembic commands ###
