"""empty message

Revision ID: 65c00837dd66
Revises: b40178469cd7
Create Date: 2023-11-06 10:56:08.797687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65c00837dd66"
down_revision: Union[str, None] = "b40178469cd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'MESON'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'CAR_REPAIRS'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'PHARMACY'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'EDUCATIONAL_SERVICES'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'HOME_APPLIANCES'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'SUPER_MARKETS'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'BAKERY'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'GROCERY_STORES'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'STATIONERY_STORES'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'DTY_FRUITS_SHOP'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'CLINICS'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'CLOTHING_STORES'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'HAIRDRESSERS'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'LASER_CENTERS'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'GOLD_AND_SILVER'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'WATCH_SHOP'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'PERFUME_AND_COLOGNE_STORE'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'DECORATION'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'COSMETIC'")

    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'MOBILE_STORE' TO 'HAIR_TRANSPLANT'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'AUDIO_AND_VIDEO_PRODUCT_STORE' TO 'BEAUTY_CLINICS'",
    )
    op.execute(
        "ALTER TYPE fieldofworktype RENAME VALUE 'KITCHEN_ACCESSORIES_STORE' TO 'DENTAL_CLINICS'",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
