"""empty message

Revision ID: b77a5b0b7b28
Revises: e658a80517f1
Create Date: 2023-10-04 14:12:02.700437

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b77a5b0b7b28"
down_revision: Union[str, None] = "e658a80517f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
