"""empty message

Revision ID: b5520d62098d
Revises: 6d2e5857cf6c
Create Date: 2023-10-03 11:57:56.028153

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5520d62098d"
down_revision: Union[str, None] = "6d2e5857cf6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("one_time_password", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "one_time_password")
    # ### end Alembic commands ###
