"""empty message

Revision ID: 328077678304
Revises: 20b9db591fba
Create Date: 2023-09-30 01:45:12.532188

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "328077678304"
down_revision: Union[str, None] = "20b9db591fba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("location", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("location", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
