"""empty message

Revision ID: bf3429f91a9a
Revises: c6b56dd7c4ec
Create Date: 2023-10-11 09:15:33.217567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.position_request.models import FieldOfWorkType

# revision identifiers, used by Alembic.
revision: str = "bf3429f91a9a"
down_revision: Union[str, None] = "c6b56dd7c4ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    field_of_work = postgresql.ENUM(FieldOfWorkType, name="fieldofworktype")
    field_of_work.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "position_request",
        sa.Column(
            "fields_of_work",
            sa.Enum(
                "MOBILE_STORE",
                "AUDIO_AND_VIDEO_PRODUCT_STORE",
                "KITCHEN_ACCESSORIES_STORE",
                "ELECTRICAL_APPLIANCES_STORE",
                "SLEEP_GOODS_STORES",
                "FURNITURE_STORES",
                "GROCERY_STORES",
                "PROTEIN_STORE",
                "CHANDELIERS_AND_ELECTRICAL_APPLIANCES",
                "SUPER_MARKETS",
                "BAKERY",
                "FRUIT_SHOPS",
                "STATIONERY_STORES",
                "DTY_FRUITS_SHOP",
                "DENTAL_CLINICS",
                "BEAUTY_CLINICS",
                "CLINICS",
                "CLOTHING_STORES",
                "HAIRDRESSERS",
                "LASER_CENTERS",
                "GOLD_AND_SILVER",
                "WATCH_SHOP",
                "PERFUME_AND_COLOGNE_STORE",
                "DECORATION",
                "COSMETIC",
                "MESON",
                "CAR_REPAIRS",
                "PHARMACY",
                "EDUCATIONAL_SERVICES",
                name="fieldofworktype",
            ),
            nullable=True,
        ),
    )
    op.drop_column("position_request", "field_of_work")
    op.add_column("transaction", sa.Column("code", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "code")
    op.add_column(
        "position_request",
        sa.Column("field_of_work", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("position_request", "fields_of_work")
    # ### end Alembic commands ###
