"""empty message

Revision ID: 146eaf81058f
Revises: fb198cb729f9
Create Date: 2023-09-30 15:36:38.353521

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "146eaf81058f"
down_revision: Union[str, None] = "fb198cb729f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("phone_number", sa.String(), nullable=True))
    op.drop_constraint("wallet_parent_id_fkey", "wallet", type_="foreignkey")
    op.drop_column("wallet", "parent_id")
    op.drop_column("wallet", "phone_number")
    op.drop_column("wallet", "name")
    op.drop_column("wallet", "dynamic_password_exp")
    op.drop_column("wallet", "dynamic_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet",
        sa.Column("dynamic_password", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "wallet",
        sa.Column(
            "dynamic_password_exp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "wallet",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "wallet",
        sa.Column("phone_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "wallet",
        sa.Column("parent_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "wallet_parent_id_fkey",
        "wallet",
        "wallet",
        ["parent_id"],
        ["id"],
    )
    op.drop_column("user", "phone_number")
    # ### end Alembic commands ###
