"""empty message

Revision ID: 1ded7222dca9
Revises: 3701b4111554
Create Date: 2023-11-13 07:33:39.321449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ded7222dca9"
down_revision: Union[str, None] = "3701b4111554"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE transactionreasonenum ADD VALUE 'CASH_BACK'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
