"""empty message

Revision ID: e6e3ac8b43fd
Revises: 67476193849e
Create Date: 2023-10-05 01:02:06.022101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6e3ac8b43fd"
down_revision: Union[str, None] = "67476193849e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cash", sa.Column("balance", sa.Integer(), nullable=True))
    op.add_column("contract", sa.Column("merchant_id", sa.UUID(), nullable=True))
    op.add_column("contract", sa.Column("agent_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "contract", "merchant", ["merchant_id"], ["id"])
    op.create_foreign_key(None, "contract", "agent", ["agent_id"], ["id"])
    op.add_column("credit", sa.Column("balance", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credit", "balance")
    op.drop_constraint(None, "contract", type_="foreignkey")
    op.drop_constraint(None, "contract", type_="foreignkey")
    op.drop_column("contract", "agent_id")
    op.drop_column("contract", "merchant_id")
    op.drop_column("cash", "balance")
    # ### end Alembic commands ###
