"""empty message

Revision ID: 993b660a650e
Revises: 7f4a84254f4d
Create Date: 2023-10-04 04:51:03.370939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "993b660a650e"
down_revision: Union[str, None] = "7f4a84254f4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contract", sa.Column("number", sa.String(), nullable=True))
    op.add_column("contract", sa.Column("name", sa.String(), nullable=True))
    op.add_column("contract", sa.Column("signatory_name", sa.String(), nullable=True))
    op.add_column(
        "contract",
        sa.Column("signatory_position", sa.String(), nullable=True),
    )
    op.add_column(
        "contract",
        sa.Column("employees_number", sa.Integer(), nullable=True),
    )
    op.create_index(op.f("ix_contract_number"), "contract", ["number"], unique=True)
    op.add_column("position_request", sa.Column("code", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_position_request_code"),
        "position_request",
        ["code"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_position_request_code"), table_name="position_request")
    op.drop_column("position_request", "code")
    op.drop_index(op.f("ix_contract_number"), table_name="contract")
    op.drop_column("contract", "employees_number")
    op.drop_column("contract", "signatory_position")
    op.drop_column("contract", "signatory_name")
    op.drop_column("contract", "name")
    op.drop_column("contract", "number")
    # ### end Alembic commands ###
