"""empty message

Revision ID: df1d35a03dd1
Revises: 7c6f522d3dca
Create Date: 2023-10-08 10:11:30.601216

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "df1d35a03dd1"
down_revision: Union[str, None] = "7c6f522d3dca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
