"""empty message

Revision ID: f9f0e04cd3d1
Revises: 78a2a128cb1e
Create Date: 2023-10-04 01:01:16.208848

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9f0e04cd3d1"
down_revision: Union[str, None] = "78a2a128cb1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("capital_transfer", sa.Column("code", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_capital_transfer_code"),
        "capital_transfer",
        ["code"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_capital_transfer_code"), table_name="capital_transfer")
    op.drop_column("capital_transfer", "code")
    # ### end Alembic commands ###
