"""empty message

Revision ID: a27406966f95
Revises: b68750c8bad9
Create Date: 2023-09-30 14:48:50.298809

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a27406966f95"
down_revision: Union[str, None] = "b68750c8bad9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ticket", sa.Column("number", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_ticket_number"), "ticket", ["number"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticket_number"), table_name="ticket")
    op.drop_column("ticket", "number")
    # ### end Alembic commands ###
