"""empty message

Revision ID: e8c9f63fd288
Revises: b77a5b0b7b28
Create Date: 2023-10-04 14:44:27.995663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8c9f63fd288"
down_revision: Union[str, None] = "b77a5b0b7b28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contract", sa.Column("organization_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "contract", "organization", ["organization_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contract", type_="foreignkey")
    op.drop_column("contract", "organization_id")
    # ### end Alembic commands ###
