"""empty message

Revision ID: d5b34299548e
Revises: d9b3c95beb59
Create Date: 2023-11-24 18:21:58.678341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5b34299548e"
down_revision: Union[str, None] = "d9b3c95beb59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("birth_date", sa.String(), nullable=True))
    op.drop_column("user_request", "last_name")
    op.drop_column("user_request", "first_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_request",
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user_request",
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("user", "birth_date")
    # ### end Alembic commands ###
