"""empty message

Revision ID: f640bd60498c
Revises: 6f9890642b62
Create Date: 2023-10-22 08:22:16.735632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f640bd60498c"
down_revision: Union[str, None] = "6f9890642b62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("installments", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "installments", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "installments", type_="foreignkey")
    op.drop_column("installments", "user_id")
    # ### end Alembic commands ###
