"""empty message

Revision ID: ec52d57cb423
Revises: af9ec98a1252
Create Date: 2023-10-18 16:16:02.127468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec52d57cb423"
down_revision: Union[str, None] = "af9ec98a1252"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "installments",
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.Column("invoice_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoice.id"]),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchant.id"]),
        sa.ForeignKeyConstraint(["parent_id"], ["installments.id"]),
        sa.ForeignKeyConstraint(["transaction_id"], ["transaction.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_installments_id"), "installments", ["id"], unique=True)
    op.create_index(
        op.f("ix_installments_number"),
        "installments",
        ["number"],
        unique=True,
    )
    op.add_column("invoice", sa.Column("installments_id", sa.UUID(), nullable=False))
    op.drop_constraint("invoice_merchant_id_fkey", "invoice", type_="foreignkey")
    op.create_foreign_key(None, "invoice", "installments", ["installments_id"], ["id"])
    op.drop_column("invoice", "merchant_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice",
        sa.Column("merchant_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "invoice", type_="foreignkey")
    op.create_foreign_key(
        "invoice_merchant_id_fkey",
        "invoice",
        "merchant",
        ["merchant_id"],
        ["id"],
    )
    op.drop_column("invoice", "installments_id")
    op.drop_index(op.f("ix_installments_number"), table_name="installments")
    op.drop_index(op.f("ix_installments_id"), table_name="installments")
    op.drop_table("installments")
    # ### end Alembic commands ###
