"""empty message

Revision ID: b9bab83d2b69
Revises: 462cdf0c1749
Create Date: 2023-10-29 13:45:39.017881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9bab83d2b69"
down_revision: Union[str, None] = "462cdf0c1749"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("total_considered_credit", sa.BigInteger(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "total_considered_credit")
    # ### end Alembic commands ###
