"""empty message

Revision ID: 16d45dfb2584
Revises: db4c452c97e8
Create Date: 2023-11-18 10:25:45.396464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16d45dfb2584"
down_revision: Union[str, None] = "db4c452c97e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("merchant", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("organization", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "is_active")
    op.drop_column("merchant", "is_active")
    op.drop_column("agent", "is_active")
    # ### end Alembic commands ###
