"""empty message

Revision ID: 33d0c2a039d3
Revises: 259ee738b404
Create Date: 2023-10-25 00:14:20.931960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33d0c2a039d3"
down_revision: Union[str, None] = "259ee738b404"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'TRANSPORTATION'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'CONFECTIONERY'")
    op.execute("ALTER TYPE fieldofworktype ADD VALUE 'RESTAURANT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE fieldofworktype DROP VALUE 'TRANSPORTATION'")
    op.execute("ALTER TYPE fieldofworktype DROP VALUE 'CONFECTIONERY'")
    op.execute("ALTER TYPE fieldofworktype DROP VALUE 'RESTAURANT'")
    # ### end Alembic commands ###
