"""empty message

Revision ID: 7f4a84254f4d
Revises: 6b0c46d43fc1
Create Date: 2023-10-04 04:08:27.761951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f4a84254f4d"
down_revision: Union[str, None] = "6b0c46d43fc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent", sa.Column("profit_rate", sa.Float(), nullable=True))
    op.drop_column("agent", "interest_rates")
    op.drop_index("ix_contract_number", table_name="contract")
    op.drop_column("contract", "name")
    op.drop_column("contract", "number")
    op.drop_column("contract", "signatory_position")
    op.drop_column("contract", "signatory_name")
    op.drop_column("contract", "employees_number")
    op.add_column("merchant", sa.Column("location_id", sa.UUID(), nullable=True))
    op.drop_index("ix_merchant_number", table_name="merchant")
    op.create_foreign_key(None, "merchant", "location", ["location_id"], ["id"])
    op.drop_column("merchant", "earned_credit")
    op.drop_column("merchant", "number")
    op.drop_index("ix_organization_name", table_name="organization")
    op.drop_column("organization", "name")
    op.drop_column("organization", "address")
    op.drop_column("organization", "contract_number")
    op.drop_column("organization", "signatory_position")
    op.drop_column("organization", "profit_rate")
    op.drop_column("organization", "signatory_name")
    op.drop_column("organization", "employees_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("employees_number", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column("signatory_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column(
            "profit_rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "organization",
        sa.Column(
            "signatory_position",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "organization",
        sa.Column("contract_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index("ix_organization_name", "organization", ["name"], unique=False)
    op.add_column(
        "merchant",
        sa.Column("number", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "merchant",
        sa.Column("earned_credit", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "merchant", type_="foreignkey")
    op.create_index("ix_merchant_number", "merchant", ["number"], unique=False)
    op.drop_column("merchant", "location_id")
    op.add_column(
        "contract",
        sa.Column("employees_number", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "contract",
        sa.Column("signatory_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "contract",
        sa.Column(
            "signatory_position",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "contract",
        sa.Column("number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "contract",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index("ix_contract_number", "contract", ["number"], unique=False)
    op.add_column(
        "agent",
        sa.Column(
            "interest_rates",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("agent", "profit_rate")
    # ### end Alembic commands ###
