"""empty message

Revision ID: 462cdf0c1749
Revises: 29cfb81665ca
Create Date: 2023-10-29 13:34:55.737575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "462cdf0c1749"
down_revision: Union[str, None] = "29cfb81665ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("personnel_number", sa.String(), nullable=True))
    op.add_column(
        "user",
        sa.Column("organizational_section", sa.String(), nullable=True),
    )
    op.add_column("user", sa.Column("job_class", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "job_class")
    op.drop_column("user", "organizational_section")
    op.drop_column("user", "personnel_number")
    # ### end Alembic commands ###
