"""empty message

Revision ID: b3ba9bf81b8e
Revises: 21c5edeff16e
Create Date: 2023-11-25 12:46:07.895386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3ba9bf81b8e"
down_revision: Union[str, None] = "21c5edeff16e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposit",
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("zibal_track_id", sa.String(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["wallet_id"], ["bank_card.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deposit_id"), "deposit", ["id"], unique=True)
    op.create_index(
        op.f("ix_deposit_wallet_id"),
        "deposit",
        ["wallet_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deposit_wallet_id"), table_name="deposit")
    op.drop_index(op.f("ix_deposit_id"), table_name="deposit")
    op.drop_table("deposit")
    # ### end Alembic commands ###
