"""empty message

Revision ID: 2c8654e46dc3
Revises: 7a32b9b4ae04
Create Date: 2023-10-03 00:00:33.837681

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c8654e46dc3"
down_revision: Union[str, None] = "7a32b9b4ae04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("contract_number", sa.String(), nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column("signatory_name", sa.String(), nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column("signatory_position", sa.String(), nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column("employees_number", sa.Integer(), nullable=True),
    )
    op.add_column("organization", sa.Column("address", sa.TEXT(), nullable=True))
    op.add_column("organization", sa.Column("location_id", sa.UUID(), nullable=True))
    op.add_column("organization", sa.Column("profit_rate", sa.Float(), nullable=True))
    op.create_foreign_key(None, "organization", "location", ["location_id"], ["id"])
    op.add_column("user", sa.Column("self_organization_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None,
        "user",
        "organization",
        ["self_organization_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "self_organization_id")
    op.drop_constraint(None, "organization", type_="foreignkey")
    op.drop_column("organization", "profit_rate")
    op.drop_column("organization", "location_id")
    op.drop_column("organization", "address")
    op.drop_column("organization", "employees_number")
    op.drop_column("organization", "signatory_position")
    op.drop_column("organization", "signatory_name")
    op.drop_column("organization", "contract_number")
    # ### end Alembic commands ###
