"""empty message

Revision ID: 4e62f0574fcf
Revises: f47960149d91
Create Date: 2023-10-04 22:19:55.648472

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "4e62f0574fcf"
down_revision: Union[str, None] = "f47960149d91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
