"""empty message

Revision ID: 5179b1150d82
Revises: 257d8c6a0b61
Create Date: 2023-11-12 13:40:35.975273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5179b1150d82"
down_revision: Union[str, None] = "257d8c6a0b61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_position_request_ability_id",
        table_name="position_request_ability",
    )
    op.drop_table("position_request_ability")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position_request_ability",
        sa.Column("position_request_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("ability_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["ability_id"],
            ["ability.id"],
            name="position_request_ability_ability_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["position_request_id"],
            ["position_request.id"],
            name="position_request_ability_position_request_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="position_request_ability_pkey"),
    )
    op.create_index(
        "ix_position_request_ability_id",
        "position_request_ability",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###
