"""empty message

Revision ID: 079790fc6319
Revises: df1d35a03dd1
Create Date: 2023-10-08 12:25:30.247817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "079790fc6319"
down_revision: Union[str, None] = "df1d35a03dd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("position_request", sa.Column("name", sa.String(), nullable=True))
    op.add_column(
        "position_request",
        sa.Column("field_of_work", sa.String(), nullable=True),
    )
    op.add_column(
        "position_request",
        sa.Column("postal_code", sa.String(), nullable=True),
    )
    op.add_column("position_request", sa.Column("tel", sa.String(), nullable=True))
    op.add_column("position_request", sa.Column("address", sa.Text(), nullable=True))
    op.add_column(
        "position_request",
        sa.Column("employee_count", sa.Integer(), nullable=True),
    )
    op.add_column("position_request", sa.Column("number", sa.Integer(), nullable=True))
    op.drop_index("ix_position_request_code", table_name="position_request")
    op.create_index(
        op.f("ix_position_request_number"),
        "position_request",
        ["number"],
        unique=True,
    )
    op.drop_column("position_request", "code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "position_request",
        sa.Column("code", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_position_request_number"), table_name="position_request")
    op.create_index(
        "ix_position_request_code",
        "position_request",
        ["code"],
        unique=False,
    )
    op.drop_column("position_request", "number")
    op.drop_column("position_request", "employee_count")
    op.drop_column("position_request", "address")
    op.drop_column("position_request", "tel")
    op.drop_column("position_request", "postal_code")
    op.drop_column("position_request", "field_of_work")
    op.drop_column("position_request", "name")
    # ### end Alembic commands ###
